# Generated by Django 4.2.10 on 2024-03-05 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testata_Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ordine', models.SmallIntegerField()),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('modificato', models.DateField(auto_now=True)),
                ('stato', models.CharField(choices=[('EV', 'Evaso'), ('NON_EVA', 'Non Evaso'), ('CANC', 'Cancellato')], default='NON_EVA', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Testate Ordini',
            },
        ),
        migrations.CreateModel(
            name='Riga_ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe_ordine', to='ordini.testata_ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.prodotti')),
            ],
            options={
                'verbose_name_plural': 'Righe Ordini',
            },
        ),
    ]
