# Generated by Django 4.2.10 on 2024-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazzino', models.CharField(max_length=50)),
                ('articolo', models.CharField(max_length=13)),
                ('descrizione', models.CharField(max_length=250)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_articoli')),
                ('qta_iniziale', models.IntegerField()),
                ('quantita', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
