# Generated by Django 4.2.10 on 2024-03-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotti',
            options={'verbose_name_plural': 'Prodotti'},
        ),
    ]
