# Generated by Django 4.2.10 on 2024-03-08 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posizione_attuale', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Consegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=100)),
                ('indirizzo_destinazione', models.CharField(max_length=200)),
                ('completata', models.BooleanField(default=False)),
                ('corriere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consegne.corriere')),
            ],
        ),
    ]
