# Generated by Django 4.2.10 on 2024-03-08 19:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consegne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriere',
            name='posizione_attuale',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(15.0873, 37.5021), srid=4326),
        ),
    ]
